[development]
address = "localhost"
port = 8000
workers = 10
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "1gIh0MPCvyT708ysgmYE+zQgAmAkQhknKbhX0q4aRQc="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 10
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
secret_key = "1gIh0MPCvyT708ysgmYE+zQgAmAkQhknKbhX0q4aRQc="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 10
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
secret_key = "1gIh0MPCvyT708ysgmYE+zQgAmAkQhknKbhX0q4aRQc="
limits = { forms = 32768 }